name: Minishell

on:
  push:
    branches: [ master, migferna, vdedios]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      
    - uses: ruby/setup-ruby@v1.57.0
      with:
        ruby-version: 2.6

    - name: Make
      run: make

    - name: Test
      uses: actions/checkout@v2
      with:
        repository: cacharle/minishell_test

    - name: Run test
      working-directory: ./minishell_test
      run: |
        pwd
        ls
