name: Minishell

on:
  push:
    branches: [ master, migferna, vdedios]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      
    - uses: ruby/setup-ruby@v1.57.0
      with:
        ruby-version: 2.6

    - name: Make
      run: make

    - name: Download Norminette
      uses: actions/checkout@v2
      with:
        repository: 42Paris/norminette
        path: norminette

    - name: Install Norminette
      working-directory: ./norminette
      run: bundle
      
    - name: Norminette
      working-directory: ./norminette
      run: norminette.rb .
