name: Minishell

on:
  push:
    branches: [ master, migferna, vdedios]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Make
      run: make

    - name: Test
      uses: actions/checkout@v2
      with:
        repository: cacharle/minishell_test
        path: ../ 

    - name: Run test
      run: ./run
