name: Minishell

on:
  push: 
   branches: [fix/leaks]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest]
    name: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
      with:
        path:  minishell

    - name: Make
      working-directory: minishell
      run: make

    - name: Test
      uses: actions/checkout@v2
      with:
        repository: cacharle/minishell_test
        path: test 

    - name: Run all test
      working-directory: test
      run: ./run